model_params:
  name: 'LSTMBetaVAE'
  in_channels: 1
  latent_dim: 128
  loss_type: 'H'
  beta: 0.01
  input_size: 32
  hidden_dims : [20]

exp_params:
  dataset: mnist
  data_path: "data/mnist_data"
  img_size: 32
  batch_size: 144 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 3

logging_params:
  save_dir: "logs/"
  name: "LSTMBetaVAE_H"
  manual_seed: 1265
